spring.application.name=Vuelos


//spring.datasource.url=jdbc:postgresql://localhost:5432/BD


//spring.datasource.username=postgres
//spring.datasource.password=


//spring.jpa.hibernate.ddl-auto=update


//server.port=8080
